import os

from dotenv import load_dotenv


load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_MODEL_NAME = os.getenv('OPENAI_MODEL_NAME')
OPENAI_MODEL_TEMPERATURE = os.getenv('OPENAI_MODEL_TEMPERATURE')

AI_CONTEXTUALIZE_PROMPT = os.getenv('AI_CONTEXTUALIZE_PROMPT')
AI_SYSTEM_PROMPT = os.getenv('AI_SYSTEM_PROMPT')

EVOLUTION_API_URL = os.getenv('EVOLUTION_API_URL')
EVOLUTION_INSTANCE_NAME = os.getenv('EVOLUTION_INSTANCE_NAME')
AUTHENTICATION_API_KEY = os.getenv('AUTHENTICATION_API_KEY')

RAG_FILES_DIR = os.getenv('RAG_FILES_DIR')
ALLOWED_PHONES = os.getenv('ALLOWED_PHONES', '')

REDIS_CACHE_URL = os.getenv('REDIS_CACHE_URL') or os.getenv('CACHE_REDIS_URI')
BUFFER_KEY_SUFFIX = os.getenv('BUFFER_KEY_SUFFIX')
BUFFER_TTL = os.getenv('BUFFER_TTL')
DEBOUNCE_SECONDS = os.getenv('DEBOUNCE_SECONDS')

DATABASE_URL = os.getenv('DATABASE_URL')
PGVECTOR_COLLECTION_NAME = os.getenv('PGVECTOR_COLLECTION_NAME')
